#!/bin/sh /etc/rc.common
START=96
STOP=12
USE_PROCD=1
start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/junwrt-parental daemon
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
reload_service() {
    touch /var/run/junwrt-parental.reload
}
service_triggers() {
    procd_add_reload_trigger junwrt-parental firewall network
}
